# Generated by Django 2.0.3 on 2018-04-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sifranti', '0003_auto_20180409_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='NacinStudija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='modul',
            name='ime',
        ),
        migrations.AddField(
            model_name='modul',
            name='predmet_dva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predmet_dva', to='sifranti.Predmet'),
        ),
        migrations.AddField(
            model_name='modul',
            name='predmet_ena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predmet_ena', to='sifranti.Predmet'),
        ),
        migrations.AddField(
            model_name='modul',
            name='predmet_tri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predmet_tri', to='sifranti.Predmet'),
        ),
    ]
