# Generated by Django 2.0.3 on 2018-04-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sifranti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('vpisna_stevilka', models.IntegerField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=30)),
                ('priimek', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('izkoriscen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('vpisna_stevilka', models.IntegerField(primary_key=True, serialize=False)),
                ('emso', models.CharField(max_length=13)),
                ('priimek', models.CharField(max_length=30)),
                ('ime', models.CharField(max_length=30)),
                ('naslov_stalno_bivalisce', models.CharField(max_length=260)),
                ('naslov_zacasno_bivalisce', models.CharField(blank=True, max_length=260, null=True)),
                ('kraj_rojstva', models.CharField(max_length=260)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('dodatno_leto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vpis',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Student')),
                ('letnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.Letnik')),
                ('nacin_studija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.NacinStudija')),
                ('studijski_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.StudijskiProgram')),
                ('studijsko_leto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.StudijskoLeto')),
                ('vrsta_studija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.VrstaStudija')),
                ('vrsta_vpisa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.VrstaVpisa')),
            ],
        ),
        migrations.CreateModel(
            name='Zeton',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Student')),
                ('pravica_do_izbire', models.BooleanField(default=False)),
                ('letnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.Letnik')),
                ('nacin_studija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.NacinStudija')),
                ('studijski_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.StudijskiProgram')),
                ('vrsta_studija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.VrstaStudija')),
                ('vrsta_vpisa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.VrstaVpisa')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='drzava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.Drzava'),
        ),
        migrations.AddField(
            model_name='student',
            name='obcina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.Obcina'),
        ),
        migrations.AddField(
            model_name='student',
            name='posta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sifranti.Posta'),
        ),
    ]
